### PR TITLE
add isResource assertion.

### PR DESCRIPTION
**Pull request by abacaphiliac**
i had to update the doc-block on `propertiesExist` so that the generated docs for that method were not incorrectly updated to `mixed`.

### CODE REVIEW

**Comment by rquadling** [comment]
All `$values` are mixed.

It is upto the assertion to validate the type.

I'm also thinking `propertiesExist` should be deprecated in favour of the default `allPropertyExists` method.

**Comment by abacaphiliac** [comment]
i had to update the second param of `propertiesExist` from mixed to array. it is an array of property names. never a single property.

normally i wouldn't blend two things like this into a single request, but when i ran the doc generator script the docs for `propertiesExist` were updated also, and i think incorrectly. changing properties to array seems correct per the functionality and ensures that there are no errant changes to the docs.

regarding deprecation, i think the names of `propertyExists` and `propertiesExist` are too similar and leads to confusion.

`propertyExists` allows you to assert that a single object has a single property, while `allPropertyExists` allows you to assert that multiple objects all have a single property.

`propertiesExist` allows you to assert that a single object has multiple properties, while `allPropertiesExists` allows you to assert that multiple objects all have multiple properties.

**Comment by rquadling** [comment]
With regard to the 'mixed'=>'array' docblock correction, I've done that manually.

**Comment by abacaphiliac** [comment]
@rquadling thank you for fixing that. sorry for lumping that into this thread : )

**Comment by rquadling** [comment]
No problem.

**Comment by rquadling** [comment]
Can you cast your eye over https://github.com/beberlei/assert/pull/219.

**Comment by abacaphiliac** [comment]
i agree with the changes in #219

**Pull request merged**
