### PR TITLE
Allow any protocol to be used in url assertion

### PR DESCRIPTION
**Pull request by fabiocarneiro**
Urls aren't only http and https, they can be of any protocol.

### CODE REVIEW

**Comment by armetiz** [comment]
What about URI like :
- //acme.com/robots.txt

See: 
- http://tools.ietf.org/html/rfc3986#section-4.2
- http://www.paulirish.com/2010/the-protocol-relative-url/

Paul Irish talked about an anti-pattern. But, still used in many cases.

What do you think about it ?

Regards;

**Comment by fabiocarneiro** [comment]
@armetiz You're right. Does it seem ok now?

**Comment by rquadling** [comment]
Can you rebase onto master please.

**Comment by localheinz** [comment]
@fabiocarneiro 

Would be nice to see this getting merged, can you resolve the conflicts?

**Comment by rquadling** [comment]
Our Url validation mirrors that of \Symfony\Component\Validator\Constraints\UrlValidator.

Having said that Image of Venn diagram of URI/URL/URN relationships

But look at https://github.com/symfony/symfony/issues/10467 for a fuller discussion as to what constitutes a URL, URN, etc. and for which RFC.

At this time, I'd prefer to keep the validation as it is. But there is now nothing stopping you from extending the Assert class and adding your own assertions, or overriding a specific assertion, for your application.

**Pull request closed without merging**
