### PR TITLE
Add not in array assertion. Closes #113.

### LINKED ISSUE #113: No notInArray() Assertion
There are `not*` assertions for lots of methods, but there isn't one for `notInArray`. I need this assertion for a project I'm working on, and, at the moment, I'm having to do this manually unless there is a better way of doing it.

Would it be possible to add this assertion?

### PR DESCRIPTION
**Pull request by raphaelstolt**

### CODE REVIEW

**Comment by rquadling** [comment]
When you add a new assertion, can you run `bin/generate_method_docs.php` to update all the docblocks and `README.md`.

**Comment by rquadling** [comment]
I think a `CONTRIBUTING.md` is required to explain the process. Care to do that too? 😃

**Comment by raphaelstolt** [comment]
Hm `php bin\generate_method_docs.php` doesn't seem to work on Windows. Will try it later on a Mac and also add a PR for a `CONTRIBUTING.md`.

**Comment by rquadling** [comment]
I'm Win/Mac too. What do you get for on Windows?

**Comment by raphaelstolt** [comment]
On Windows it doesn't throw an error per se, but it also doesn't update the docblocks and `README.md`. Meaning when doing a `git status` after running `composer generate-docs` or `php bin\generate_method_docs.php` no modifications are shown. Though when `print_r`'ing the result after the reflection part the generated content seem to be correct.

Might need some further investigation (more probably in a separate issue). Didn't have time to test it on a Mac yet.

**Comment by raphaelstolt** [comment]
Works flawless on a Mac. I guess on Windows it's a weird combination of `preg_replace` and the `line endings` of the files.

**Comment by rquadling** [comment]
I'm on Windows with this OK. PICNIC? :-D

**Pull request merged**
