### PR TITLE
Implemented keyNotExists assertion

### PR DESCRIPTION
**Pull request by christeredvartsen**
This pull request implements a `keyNotExists` assertion. Tests are included.

### CODE REVIEW

**Comment by rquadling** [comment]
Can you rebase against master please?

**Comment by christeredvartsen** [comment]
Done.

**Comment by rquadling** [comment]
And take a look at the [CONTRIBUTING](https://github.com/beberlei/assert/blob/master/CONTRIBUTING.md) readme.

**Comment by rquadling** [comment]
Oops. Didn't mean to close.

**Comment by christeredvartsen** [comment]
Sorry, didn't notice that! Done! :)

**Pull request merged**
