### PR TITLE
User and password on URLs can contain dots

### PR DESCRIPTION
**Pull request by fedeisas**
https://tools.ietf.org/html/rfc7617#section-2.1

### CODE REVIEW

**Comment by rquadling** [comment]
Thank you for this.

I've submitted the same issue against Symfony as that is where we got our regexes.

Once accepted there, I'll accept it here.

In the meantime, can you take a look at https://github.com/symfony/symfony/pull/24589 and copy the unit test changes please to this PR.

**Comment by fedeisas** [comment]
@rquadling thanks! I've copied the unit tests. It's already merged on the Symfony repo.

**Comment by rquadling** [comment]
Thank you for this.

**Comment by rquadling** [comment]
I'll do a release shortly.

**Pull request merged**
