### PR TITLE
Fix: Run steps in appropriate sections

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs build steps on Travis in appropriate sections

💁 For reference, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle.

### CODE REVIEW

**Comment by rquadling** [comment]
I'm not 100% travis guru (read that as I try and get things working as best I can).

I'm collaborator on another project and they have ...

```
before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable ${COMPOSER_FLAGS}
```

The `travis_retry` command ... is this worth having?

**Comment by localheinz** [comment]
@rquadling 

Never needed it, but that doesn't mean that others may not need it.

Personally, I wouldn't bother.

**Comment by staabm** [comment]
I would add travis_retry when your build gets unstable because of travis errors. wouldnt add it in case you didn't suffer from the problems it solves.

**Comment by rquadling** [comment]
Thank you.

**Comment by rquadling** [comment]
Looking at https://travis-ci.org/beberlei/assert/jobs/148124941, you can see there are 2 `composer self-update` being ran.

And this seems to have been the case for a long while! It would seem as if Travis is preparing composer for us.

**Pull request merged**
