### PR TITLE
Added Assertion::interfaceExists

### PR DESCRIPTION
**Pull request by sisve**
Added an interfaceExists assertion.

I'm unsure about the value of the INVALID_INTERFACE constant; are they structured in a specific way?

### CODE REVIEW

**Comment by rquadling** [comment]
Can you rebase your feature on to the current master please.

**Comment by sisve** [comment]
Yes, I will do this later today... (being intentionally vague about local timezones and the concept of "day") =)

**Comment by rquadling** [comment]
Your vagueness has been recorded and will be used against you at some time. Maybe.

**Comment by sisve** [comment]
I've misplaced the original repository, branch and vibe this pull request was based on, so I redid it in https://github.com/beberlei/assert/pull/173 . I'm closing this one.

**Pull request closed without merging**
