### PR TITLE
Add missing assertion docblock entries.

### PR DESCRIPTION
**Pull request by rquadling**
Add missing assertions to docblocks, allowing IDEs to successfully pass static analysis checks

### CODE REVIEW

**Comment by stof** [comment]
have you done it by hand, or by running ``bin/generate_method_docs.php`` ? If done by hand, please run the script instead, to ensure that they are added in the place where the script adds them

**Comment by rquadling** [comment]
Used the script. I ran it to see what it did! Ha! Fixes stuff. That's what it did! I then made up a use case for running it. Et voila! A reason for the patch was found.

In truth though, PHPStorm was giving me a missing method for date() assertion and that is what I was trying to find a fix for.

**Comment by rquadling** [comment]
Can this PR be merged please?

**Comment by stof** [comment]
@rquadling this PR makes sense, but I'm not a maintainer of this repo. So I'm not the one merging it (I'm the author of this script though :smile:)

**Comment by rquadling** [comment]
If this package needs a new maintainer, I'm happy to take over. I use this daily and would be happy to continue supporting/enhancing it.

**Pull request merged**
