### PR TITLE
Fixes #136 - Make all assertions return true on success

### LINKED ISSUE #136: Make all assertions return true on success, so that it can be used inside PHP 7 assert()
``` php
/**
 * @param ThingInterface[] $things
 */
public function __construct(array $things)
{
    // no-op on production environment! :D
    assert(Assertion::allIsInstanceOf($things, ThingInterface::class));

    $this->things = $things;
}
```

@beberlei what do you think?

### PR DESCRIPTION
**Pull request by VaclavSir**
This pull request:
- Adds `return true;` at the end of each assertion.
- Updates `@return` annotations accordingly.
- Adds `assertTrue()` to all tests of passing assertions.

See #136

### CODE REVIEW

**Comment by VaclavSir** [comment]
I can't figure out why the PHP 7.1 build is failing. Possibly a PHP bug, for some reason it parses the time wrong: https://3v4l.org/i0hnd

**Comment by VaclavSir** [comment]
I reported the bug: https://bugs.php.net/bug.php?id=73426

**Comment by rquadling** [comment]
That bug is now fixed : http://git.php.net/?p=php-src.git;a=commit;h=1d1a7feecfab42bb3a0657ed684e11abeae45315

**Comment by rquadling** [comment]
Strangely enough php-semver-checker suggests this is only a patch release. So I'm going with that.

The PHP7.1 issue has been fixed, so we can ignore the failure there.

**Pull request merged**
