### PR TITLE
Allow custom exception for assertion

### PR DESCRIPTION
**Pull request by blazarecki**
This PR allow to use specific exception for assert.

``` php
<?php

Assertion::integer(1, "Message", "\InvalidArgumentException");
```

It's allow to use multiple catch in try catch blocks.

``` php
<?php

try {
    Assertion::integer($value, "The pressure of gas is measured in integers.", "\InvalidArgumentException");
    Assertion::notNull($value, "The pressure of gas should not be null.", "CustomException");
} catch(\InvalidArgumentException $e) {
    // do stuff
} catch (CustomException $e) {
    // do other stuff
}
```

### CODE REVIEW

**Comment by rquadling** [comment]
You can now create your own assertions and assertion exceptions, so there would seem no reason for this pull request.

Please look at the current release and come back if there is anything you think that is missing.

Thank you for your PR.

**Comment by dennis-fedco** [comment]
I have a question.  I have a need to catch exceptions and filter exceptions based on some mechanism, i.e. exception type, or code, or in the worst case, message.

For example I have the following code to ensure that some characteristics of my `Crate` object are valid.  

    Assert::that($weight)->greaterThan(0, "Weight is 0");
    Assert::that($height)->greaterThan(0, "Height is 0");
    Assert::that($price)->greaterThan(0, "Price is 0");

When there is an error, a `Crate` is not created and throws exception.  However in my use case when weight is unknown or 0, it makes sence to still create the Crate object, because dimensions of it are more important then the weight.  In other words, I want to know when the `$weight`-related exception has been thrown, and ignore that exception only.  

How?

Looking at docs, I went ahead and created `CrateWeightAssert`, `CrateWeightAssertion`, `CrateWeightException`, and it seems to be overkill for my single use case.  Is there a way to only have `CrateWeightException`? 

if this is unclear, my problem is such - I want to filter exceptions and don't want to base it on string response, as that seems hacky and string response can change.  In its native state the test suite throws these Exceptions:

    Assert\InvalidArgumentException: Weight is 0
    Assert\InvalidArgumentException: Height is 0
    Assert\InvalidArgumentException: Price is 0

I want to be able to throw my own Exception, and I was able to do so but with the overhead of extending Assert and Assertion class with my own, which seemed like overkill, hence I wanted confirmation on if I was doing it correctly.

**Comment by rquadling** [comment]
Each exception that is thrown has an exception code 
```
    const INVALID_FLOAT = 9;
    const INVALID_INTEGER = 10;
    const INVALID_DIGIT = 11;
    const INVALID_INTEGERISH = 12;
    const INVALID_BOOLEAN = 13;
    const VALUE_EMPTY = 14;
    const VALUE_NULL = 15;
``` (a snippet of the ones defined in `\Assert\Assertion`.

So, if you have a CrateException and the a set of constants for each type of thing wrong with the crate, you can then.

You can then have a CrateAssertion which is given a Crate to validate. It validates all the things using a lazy assertion and then returns the entire set of validation issues in 1 exception.

**Comment by rquadling** [comment]
Also, if something is optional (like the weight), then checking the value is probably only worth doing if non zero. So maybe using `\Assert\Assertion::greaterOrEqualThan(0, $create->weight)`

**Pull request closed without merging**
