### PR TITLE
Add date assertion with tests. fix #102

### LINKED ISSUE #102: Assertion "date" missing
Hello,

I think an assertion for valid dates is missing `Assertion::date($value, $format)`.
Is anyone able to add this please? :)

### PR DESCRIPTION
**Pull request by Lexty**
Fix #102

### CODE REVIEW

**Comment by beberlei** [comment]
Rebase please, this is a more useful date assertion than the other one I have seen in another PR. I would merge it, please ping me on twitter when its done, so i dont forget.

**Comment by Lexty** [comment]
You mean rebase others changes to my branch or rebase my changes to master and make new PR? I did the first one.

**Comment by beberlei** [comment]
@Lexty rebase onto the current master please, your PR now has all the code in master since you forked. Its all a bit hard to read. Can you redo the PR with just your commits?

**Comment by Lexty** [comment]
@beberlei It's done. #115

**Pull request closed without merging**
